# Generated by Django 5.2.5 on 2025-10-16 23:04

import django.contrib.auth.validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovalRoute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='承認ルート名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '承認ルート',
                'verbose_name_plural': '承認ルート一覧',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='会社名')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='郵便番号')),
                ('address', models.TextField(blank=True, verbose_name='住所')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='代表メールアドレス')),
                ('tax_number', models.CharField(blank=True, max_length=20, verbose_name='法人番号')),
                ('logo', models.ImageField(blank=True, upload_to='company_logos/', verbose_name='会社ロゴ')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '会社',
                'verbose_name_plural': '会社一覧',
            },
        ),
        migrations.CreateModel(
            name='CustomerCompany',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='会社名')),
                ('business_type', models.CharField(choices=[('subcontractor', '協力会社'), ('supplier', '資材サプライヤー'), ('service', 'サービス業者'), ('consultant', 'コンサルタント'), ('other', 'その他')], max_length=20, verbose_name='業種')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='郵便番号')),
                ('address', models.TextField(blank=True, verbose_name='住所')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('email', models.EmailField(max_length=254, verbose_name='代表メールアドレス')),
                ('tax_number', models.CharField(blank=True, max_length=20, verbose_name='法人番号')),
                ('bank_name', models.CharField(blank=True, max_length=50, verbose_name='銀行名')),
                ('bank_branch', models.CharField(blank=True, max_length=50, verbose_name='支店名')),
                ('bank_account', models.CharField(blank=True, max_length=20, verbose_name='口座番号')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '顧客会社',
                'verbose_name_plural': '顧客会社一覧',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('user_type', models.CharField(choices=[('internal', '社内ユーザー'), ('customer', '顧客ユーザー')], default='internal', max_length=10, verbose_name='ユーザー種別')),
                ('position', models.CharField(blank=True, choices=[('president', '社長'), ('director', '取締役'), ('manager', '部長'), ('supervisor', '課長'), ('staff', '一般社員'), ('accountant', '経理担当'), ('admin', 'システム管理者')], max_length=20, verbose_name='役職')),
                ('is_primary_contact', models.BooleanField(default=False, verbose_name='主担当者')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='電話番号')),
                ('is_active_user', models.BooleanField(default=True, verbose_name='アクティブ')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.company', verbose_name='所属会社')),
                ('customer_company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.customercompany', verbose_name='顧客会社')),
            ],
            options={
                'verbose_name': 'ユーザー',
                'verbose_name_plural': 'ユーザー一覧',
            },
        ),
        migrations.CreateModel(
            name='ApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_order', models.IntegerField(verbose_name='ステップ順序')),
                ('step_name', models.CharField(max_length=50, verbose_name='ステップ名')),
                ('approver_position', models.CharField(choices=[('president', '社長'), ('director', '取締役'), ('manager', '部長'), ('supervisor', '課長'), ('staff', '一般社員'), ('accountant', '経理担当'), ('admin', 'システム管理者')], max_length=20, verbose_name='承認者役職')),
                ('is_required', models.BooleanField(default=True, verbose_name='必須ステップ')),
                ('timeout_days', models.IntegerField(default=7, verbose_name='承認期限（日数）')),
                ('approver_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='指定承認者')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='invoices.approvalroute')),
            ],
            options={
                'verbose_name': '承認ステップ',
                'verbose_name_plural': '承認ステップ一覧',
                'ordering': ['step_order'],
                'unique_together': {('route', 'step_order')},
            },
        ),
        migrations.AddField(
            model_name='approvalroute',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.company'),
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='部署名')),
                ('code', models.CharField(blank=True, max_length=20, verbose_name='部署コード')),
                ('manager_name', models.CharField(blank=True, max_length=50, verbose_name='部署長名')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='invoices.company')),
            ],
            options={
                'verbose_name': '部署',
                'verbose_name_plural': '部署一覧',
                'unique_together': {('company', 'code')},
            },
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.department', verbose_name='所属部署'),
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=50, unique=True, verbose_name='請求書番号')),
                ('unique_url', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='固有URL')),
                ('unique_number', models.CharField(max_length=20, unique=True, verbose_name='管理番号')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='請求金額')),
                ('tax_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, verbose_name='税額')),
                ('issue_date', models.DateField(verbose_name='発行日')),
                ('due_date', models.DateField(verbose_name='支払期日')),
                ('project_name', models.CharField(blank=True, max_length=100, verbose_name='工事名')),
                ('project_code', models.CharField(blank=True, max_length=50, verbose_name='工事コード')),
                ('department_code', models.CharField(blank=True, max_length=20, verbose_name='部門コード')),
                ('file', models.FileField(upload_to='invoices/', verbose_name='請求書ファイル')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('submitted', '送付済み'), ('received', '受付済み'), ('pending_approval', '承認待ち'), ('approved', '承認済み'), ('rejected', '却下'), ('returned', '差し戻し'), ('payment_preparing', '支払い準備中'), ('paid', '支払い済み')], default='draft', max_length=20, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('approval_route', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.approvalroute', verbose_name='承認ルート')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_invoices', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('current_approval_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.approvalstep', verbose_name='現在の承認ステップ')),
                ('customer_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.customercompany', verbose_name='請求元会社')),
                ('receiving_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.company', verbose_name='請求先会社')),
            ],
            options={
                'verbose_name': '請求書',
                'verbose_name_plural': '請求書一覧',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ApprovalHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('submitted', '送付'), ('approved', '承認'), ('rejected', '却下'), ('returned', '差し戻し'), ('commented', 'コメント')], max_length=20, verbose_name='アクション')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='実行日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='実行者')),
                ('approval_step', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.approvalstep')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_histories', to='invoices.invoice')),
            ],
            options={
                'verbose_name': '承認履歴',
                'verbose_name_plural': '承認履歴一覧',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_type', models.CharField(choices=[('general', '一般コメント'), ('approval', '承認関連'), ('payment', '支払い関連'), ('correction', '修正依頼'), ('internal_memo', '内部メモ')], default='general', max_length=20, verbose_name='コメント種別')),
                ('comment', models.TextField(verbose_name='コメント')),
                ('is_private', models.BooleanField(default=False, verbose_name='社内限定')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='投稿日時')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='invoices.invoice')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='投稿者')),
            ],
            options={
                'verbose_name': '請求書コメント',
                'verbose_name_plural': '請求書コメント一覧',
                'ordering': ['-timestamp'],
            },
        ),
    ]
