# Generated by Django 5.2.5 on 2025-10-29 09:17

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='construction_site_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='工事現場名'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_date',
            field=models.DateField(blank=True, null=True, verbose_name='請求日'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='notes',
            field=models.TextField(blank=True, verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True, verbose_name='支払予定日'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='subtotal',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=15, verbose_name='小計'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='total_amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=15, verbose_name='合計金額'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='請求金額'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='due_date',
            field=models.DateField(blank=True, null=True, verbose_name='支払期日'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='file',
            field=models.FileField(blank=True, upload_to='invoices/', verbose_name='請求書ファイル'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='請求書番号'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='issue_date',
            field=models.DateField(blank=True, null=True, verbose_name='発行日'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='tax_amount',
            field=models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=15, verbose_name='消費税'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='unique_number',
            field=models.CharField(blank=True, max_length=20, unique=True, verbose_name='管理番号'),
        ),
        migrations.CreateModel(
            name='ConstructionSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='現場名')),
                ('location', models.TextField(blank=True, verbose_name='所在地')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_sites', to='invoices.company', verbose_name='発注会社')),
            ],
            options={
                'verbose_name': '工事現場',
                'verbose_name_plural': '工事現場一覧',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='construction_site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.constructionsite', verbose_name='工事現場'),
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField(verbose_name='項番')),
                ('description', models.CharField(max_length=200, verbose_name='品名・摘要')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='数量')),
                ('unit', models.CharField(default='式', max_length=20, verbose_name='単位')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=15, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='単価')),
                ('amount', models.DecimalField(decimal_places=0, default=Decimal('0'), max_digits=15, verbose_name='金額')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.invoice', verbose_name='請求書')),
            ],
            options={
                'verbose_name': '請求明細',
                'verbose_name_plural': '請求明細一覧',
                'ordering': ['item_number'],
            },
        ),
    ]
