# Generated by Django 5.2.5 on 2025-11-07 01:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0002_invoice_construction_site_name_invoice_invoice_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoice',
            name='amount',
        ),
        migrations.AddField(
            model_name='approvalroute',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='デフォルトルート'),
        ),
        migrations.AddField(
            model_name='constructionsite',
            name='supervisor',
            field=models.ForeignKey(blank=True, limit_choices_to={'position': 'site_supervisor', 'user_type': 'internal'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='supervised_sites', to=settings.AUTH_USER_MODEL, verbose_name='現場監督'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='current_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_approvals', to=settings.AUTH_USER_MODEL, verbose_name='現在の承認者'),
        ),
        migrations.AlterField(
            model_name='approvalhistory',
            name='action',
            field=models.CharField(choices=[('submitted', '提出'), ('approved', '承認'), ('rejected', '却下'), ('returned', '差し戻し'), ('commented', 'コメント')], max_length=20, verbose_name='アクション'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='approver_position',
            field=models.CharField(choices=[('site_supervisor', '現場監督'), ('managing_director', '常務取締役'), ('senior_managing_director', '専務取締役'), ('president', '代表取締役社長'), ('accountant', '経理担当'), ('director', '取締役'), ('manager', '部長'), ('supervisor', '課長'), ('staff', '一般社員'), ('admin', 'システム管理者')], max_length=30, verbose_name='承認者役職'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='approver_user',
            field=models.ForeignKey(blank=True, help_text='特定のユーザーを指定する場合（オプション）', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='指定承認者'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', '下書き'), ('submitted', '提出済み'), ('pending_approval', '承認待ち'), ('approved', '承認済み'), ('rejected', '却下'), ('returned', '差し戻し'), ('payment_preparing', '支払い準備中'), ('paid', '支払い済み')], default='draft', max_length=20, verbose_name='ステータス'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('site_supervisor', '現場監督'), ('managing_director', '常務取締役'), ('senior_managing_director', '専務取締役'), ('president', '代表取締役社長'), ('accountant', '経理担当'), ('director', '取締役'), ('manager', '部長'), ('supervisor', '課長'), ('staff', '一般社員'), ('admin', 'システム管理者')], max_length=30, verbose_name='役職'),
        ),
    ]
