# Generated by Django 5.2.5 on 2025-11-08 04:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0003_remove_invoice_amount_approvalroute_is_default_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='フィールド名')),
                ('field_type', models.CharField(choices=[('text', 'テキスト'), ('number', '数値'), ('date', '日付'), ('select', '選択'), ('checkbox', 'チェックボックス')], max_length=20, verbose_name='フィールドタイプ')),
                ('is_required', models.BooleanField(default=False, verbose_name='必須')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('help_text', models.CharField(blank=True, max_length=200, verbose_name='ヘルプテキスト')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.company', verbose_name='会社')),
            ],
            options={
                'verbose_name': 'カスタムフィールド',
                'verbose_name_plural': 'カスタムフィールド',
                'db_table': 'custom_fields',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='テンプレート名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('is_default', models.BooleanField(default=False, verbose_name='デフォルト')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.company', verbose_name='会社')),
            ],
            options={
                'verbose_name': '請求書テンプレート',
                'verbose_name_plural': '請求書テンプレート',
                'db_table': 'invoice_templates',
                'ordering': ['-is_default', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoices.invoicetemplate', verbose_name='テンプレート'),
        ),
        migrations.CreateModel(
            name='MonthlyInvoicePeriod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年')),
                ('month', models.IntegerField(help_text='1-12', verbose_name='月')),
                ('deadline_date', models.DateField(verbose_name='締切日')),
                ('is_closed', models.BooleanField(default=False, verbose_name='締め済み')),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='締め日時')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='closed_periods', to=settings.AUTH_USER_MODEL, verbose_name='締め実行者')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.company', verbose_name='会社')),
            ],
            options={
                'verbose_name': '月次請求期間',
                'verbose_name_plural': '月次請求期間',
                'db_table': 'monthly_invoice_periods',
                'ordering': ['-year', '-month'],
                'unique_together': {('company', 'year', 'month')},
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='invoice_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='invoices.monthlyinvoiceperiod', verbose_name='請求期間'),
        ),
        migrations.CreateModel(
            name='PDFGenerationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generated_at', models.DateTimeField(auto_now_add=True, verbose_name='生成日時')),
                ('file_size', models.IntegerField(blank=True, null=True, verbose_name='ファイルサイズ(bytes)')),
                ('generated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='生成者')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_logs', to='invoices.invoice', verbose_name='請求書')),
            ],
            options={
                'verbose_name': 'PDF生成履歴',
                'verbose_name_plural': 'PDF生成履歴',
                'db_table': 'pdf_generation_logs',
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='TemplateField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='フィールド名')),
                ('field_type', models.CharField(choices=[('text', 'テキスト'), ('number', '数値'), ('date', '日付'), ('select', '選択'), ('textarea', 'テキストエリア')], max_length=20, verbose_name='フィールドタイプ')),
                ('is_required', models.BooleanField(default=False, verbose_name='必須')),
                ('default_value', models.CharField(blank=True, max_length=200, verbose_name='デフォルト値')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('help_text', models.CharField(blank=True, max_length=200, verbose_name='ヘルプテキスト')),
                ('choices', models.TextField(blank=True, help_text='カンマ区切り (例: 銀行振込,現金,小切手)', verbose_name='選択肢')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='invoices.invoicetemplate', verbose_name='テンプレート')),
            ],
            options={
                'verbose_name': 'テンプレートフィールド',
                'verbose_name_plural': 'テンプレートフィールド',
                'db_table': 'template_fields',
                'ordering': ['display_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CustomFieldValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.TextField(verbose_name='値')),
                ('custom_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.customfield', verbose_name='カスタムフィールド')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_values', to='invoices.invoice', verbose_name='請求書')),
            ],
            options={
                'verbose_name': 'カスタムフィールド値',
                'verbose_name_plural': 'カスタムフィールド値',
                'db_table': 'custom_field_values',
                'unique_together': {('invoice', 'custom_field')},
            },
        ),
    ]
