# Generated by Django 5.2.5 on 2025-11-27 06:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0004_customfield_invoicetemplate_invoice_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConstructionType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='工種コード')),
                ('name', models.CharField(max_length=50, verbose_name='工種名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用回数')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '工種',
                'verbose_name_plural': '工種一覧',
                'db_table': 'construction_types',
                'ordering': ['-usage_count', 'display_order', 'name'],
            },
        ),
        migrations.AddField(
            model_name='constructionsite',
            name='budget_alert_threshold',
            field=models.IntegerField(default=90, help_text='この割合を超えたらアラートを表示', verbose_name='予算アラート閾値(%)'),
        ),
        migrations.AddField(
            model_name='constructionsite',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='completed_sites', to=settings.AUTH_USER_MODEL, verbose_name='完成処理者'),
        ),
        migrations.AddField(
            model_name='constructionsite',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='完成日'),
        ),
        migrations.AddField(
            model_name='constructionsite',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='完成'),
        ),
        migrations.AddField(
            model_name='constructionsite',
            name='total_budget',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='実行予算総額'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_check_result',
            field=models.CharField(choices=[('not_checked', '未照合'), ('matched', '一致'), ('over', '上乗せあり'), ('under', '減額あり'), ('no_order', '注文書なし')], default='not_checked', max_length=20, verbose_name='金額照合結果'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='amount_difference',
            field=models.DecimalField(decimal_places=0, default=0, help_text='請求額と注文書金額の差（正:上乗せ、負:減額）', max_digits=15, verbose_name='金額差異'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='batch_approval_scheduled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='一斉承認予定日時'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='construction_type_other',
            field=models.CharField(blank=True, help_text='工種が「その他」の場合に入力', max_length=100, verbose_name='工種（その他）'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='correction_deadline',
            field=models.DateTimeField(blank=True, help_text='受領日時から2日後', null=True, verbose_name='訂正期限'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='document_type',
            field=models.CharField(choices=[('invoice', '請求書'), ('delivery_note', '納品書')], default='invoice', max_length=20, verbose_name='書類タイプ'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_correction_allowed',
            field=models.BooleanField(default=True, verbose_name='訂正可能'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='received_at',
            field=models.DateTimeField(blank=True, help_text='請求書を受領した日時', null=True, verbose_name='受領日時'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='safety_cooperation_fee',
            field=models.DecimalField(decimal_places=0, default=0, help_text='10万円以上の場合、請求額の3/1000', max_digits=15, verbose_name='安全衛生協力会費'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='safety_fee_notified',
            field=models.BooleanField(default=False, verbose_name='協力会費通知済み'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_save_data',
            field=models.BooleanField(default=True, help_text='False: 閲覧・承認のみ可能（ダウンロード不可）', verbose_name='データ保存可能'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_super_admin',
            field=models.BooleanField(default=False, help_text='全機能へのアクセス権限（期限切れ書類の編集、全データ閲覧など）', verbose_name='スーパー管理者'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='status',
            field=models.CharField(choices=[('draft', '下書き'), ('submitted', '提出済み'), ('pending_approval', '承認待ち'), ('pending_batch_approval', '一斉承認待ち'), ('approved', '承認済み'), ('rejected', '却下'), ('returned', '差し戻し'), ('payment_preparing', '支払い準備中'), ('paid', '支払い済み')], default='draft', max_length=30, verbose_name='ステータス'),
        ),
        migrations.CreateModel(
            name='BatchApprovalSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_datetime', models.DateTimeField(verbose_name='一斉承認予定日時')),
                ('is_executed', models.BooleanField(default=False, verbose_name='実行済み')),
                ('executed_at', models.DateTimeField(blank=True, null=True, verbose_name='実行日時')),
                ('target_supervisor_count', models.IntegerField(default=0, verbose_name='対象監督者数')),
                ('target_invoice_count', models.IntegerField(default=0, verbose_name='対象請求書数')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('executed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='実行者')),
                ('period', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='batch_schedules', to='invoices.monthlyinvoiceperiod', verbose_name='請求期間')),
            ],
            options={
                'verbose_name': '一斉承認スケジュール',
                'verbose_name_plural': '一斉承認スケジュール一覧',
                'db_table': 'batch_approval_schedules',
                'ordering': ['-scheduled_datetime'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='construction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.constructiontype', verbose_name='工種'),
        ),
        migrations.CreateModel(
            name='InvoiceChangeHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('change_type', models.CharField(choices=[('created', '作成'), ('updated', '更新'), ('amount_changed', '金額変更'), ('status_changed', 'ステータス変更'), ('item_added', '明細追加'), ('item_removed', '明細削除'), ('item_modified', '明細変更'), ('correction', '訂正')], max_length=30, verbose_name='変更種別')),
                ('field_name', models.CharField(blank=True, max_length=100, verbose_name='変更フィールド')),
                ('old_value', models.TextField(blank=True, verbose_name='変更前の値')),
                ('new_value', models.TextField(blank=True, verbose_name='変更後の値')),
                ('change_reason', models.TextField(verbose_name='変更理由')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='変更日時')),
                ('changed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='変更者')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_histories', to='invoices.invoice', verbose_name='請求書')),
            ],
            options={
                'verbose_name': '請求書変更履歴',
                'verbose_name_plural': '請求書変更履歴一覧',
                'db_table': 'invoice_change_histories',
                'ordering': ['-changed_at'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='注文書番号')),
                ('subtotal', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='小計')),
                ('tax_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='消費税')),
                ('total_amount', models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='合計金額')),
                ('issue_date', models.DateField(verbose_name='発行日')),
                ('delivery_date', models.DateField(blank=True, null=True, verbose_name='納期')),
                ('status', models.CharField(choices=[('draft', '下書き'), ('issued', '発行済み'), ('accepted', '受諾済み'), ('completed', '完了'), ('cancelled', 'キャンセル')], default='draft', max_length=20, verbose_name='ステータス')),
                ('pdf_file', models.FileField(blank=True, upload_to='purchase_orders/', verbose_name='注文書PDF')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('construction_site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.constructionsite', verbose_name='工事現場')),
                ('construction_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.constructiontype', verbose_name='工種')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_orders', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
                ('customer_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.customercompany', verbose_name='発注先会社')),
                ('issuing_company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoices.company', verbose_name='発注元会社')),
            ],
            options={
                'verbose_name': '注文書',
                'verbose_name_plural': '注文書一覧',
                'db_table': 'purchase_orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='invoice',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='invoices.purchaseorder', verbose_name='注文書'),
        ),
        migrations.CreateModel(
            name='PurchaseOrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_number', models.IntegerField(verbose_name='項番')),
                ('description', models.CharField(max_length=200, verbose_name='品名・摘要')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='数量')),
                ('unit', models.CharField(default='式', max_length=20, verbose_name='単位')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='単価')),
                ('amount', models.DecimalField(decimal_places=0, max_digits=15, verbose_name='金額')),
                ('purchase_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='invoices.purchaseorder', verbose_name='注文書')),
            ],
            options={
                'verbose_name': '注文書明細',
                'verbose_name_plural': '注文書明細一覧',
                'db_table': 'purchase_order_items',
                'ordering': ['item_number'],
            },
        ),
        migrations.CreateModel(
            name='SystemNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('reminder', 'リマインド'), ('deadline', '期限通知'), ('approval', '承認通知'), ('alert', 'アラート'), ('info', '情報')], default='info', max_length=20, verbose_name='通知種別')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10, verbose_name='優先度')),
                ('title', models.CharField(max_length=200, verbose_name='タイトル')),
                ('message', models.TextField(verbose_name='メッセージ')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='アクションURL')),
                ('is_read', models.BooleanField(default=False, verbose_name='既読')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='既読日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='受信者')),
                ('related_invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='invoices.invoice', verbose_name='関連請求書')),
            ],
            options={
                'verbose_name': 'システム通知',
                'verbose_name_plural': 'システム通知一覧',
                'db_table': 'system_notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AccessLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('login', 'ログイン'), ('logout', 'ログアウト'), ('view', '閲覧'), ('create', '作成'), ('update', '更新'), ('delete', '削除'), ('download', 'ダウンロード'), ('export', 'エクスポート'), ('approve', '承認'), ('reject', '却下')], max_length=20, verbose_name='アクション')),
                ('resource_type', models.CharField(max_length=50, verbose_name='リソース種別')),
                ('resource_id', models.CharField(blank=True, max_length=50, verbose_name='リソースID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('user_agent', models.TextField(blank=True, verbose_name='ユーザーエージェント')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='詳細情報')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'アクセスログ',
                'verbose_name_plural': 'アクセスログ一覧',
                'db_table': 'access_logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', 'timestamp'], name='access_logs_user_id_a657f9_idx'), models.Index(fields=['action', 'timestamp'], name='access_logs_action_be81ba_idx'), models.Index(fields=['resource_type', 'resource_id'], name='access_logs_resourc_b5d576_idx')],
            },
        ),
    ]
