# Generated by Django 5.2.5 on 2025-11-27 07:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0005_constructiontype_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionsite',
            name='budget_alert_100_notified',
            field=models.BooleanField(default=False, verbose_name='100%超過通知済み'),
        ),
        migrations.AddField(
            model_name='constructionsite',
            name='budget_alert_80_notified',
            field=models.BooleanField(default=False, verbose_name='80%到達通知済み'),
        ),
        migrations.AddField(
            model_name='constructionsite',
            name='budget_alert_90_notified',
            field=models.BooleanField(default=False, verbose_name='90%到達通知済み'),
        ),
        migrations.AddField(
            model_name='invoicecomment',
            name='mentioned_users',
            field=models.ManyToManyField(blank=True, related_name='mentioned_in_comments', to=settings.AUTH_USER_MODEL, verbose_name='メンションされたユーザー'),
        ),
    ]
