# Generated by Django 5.2.5 on 2025-11-27 07:22

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0006_constructionsite_budget_alert_100_notified_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('budget_year', models.IntegerField(verbose_name='予算年度')),
                ('budget_month', models.IntegerField(blank=True, help_text='NULLの場合は年間予算', null=True, verbose_name='予算月')),
                ('budget_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='予算金額')),
                ('allocated_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='配賦済み金額')),
                ('remaining_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='残予算')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '予算',
                'verbose_name_plural': '予算一覧',
                'db_table': 'budgets',
                'ordering': ['-budget_year', '-budget_month'],
            },
        ),
        migrations.CreateModel(
            name='ConstructionTypeUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usage_count', models.IntegerField(default=0, verbose_name='使用回数')),
                ('last_used_at', models.DateTimeField(blank=True, null=True, verbose_name='最終使用日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '工種使用履歴',
                'verbose_name_plural': '工種使用履歴一覧',
                'db_table': 'construction_type_usages',
                'ordering': ['-usage_count', '-last_used_at'],
            },
        ),
        migrations.CreateModel(
            name='FileAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255, verbose_name='ファイル名')),
                ('file_path', models.FileField(upload_to='attachments/%Y/%m/', verbose_name='ファイル')),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('image', '画像'), ('excel', 'Excel'), ('word', 'Word'), ('other', 'その他')], default='other', max_length=20, verbose_name='ファイルタイプ')),
                ('file_size', models.BigIntegerField(default=0, verbose_name='ファイルサイズ(bytes)')),
                ('mime_type', models.CharField(blank=True, max_length=100, verbose_name='MIMEタイプ')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
            ],
            options={
                'verbose_name': '添付ファイル',
                'verbose_name_plural': '添付ファイル一覧',
                'db_table': 'file_attachments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceApprovalStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.IntegerField(verbose_name='ステップ番号')),
                ('approver_role', models.CharField(choices=[('supervisor', '現場監督'), ('manager', '部門長'), ('accounting', '経理'), ('executive', '役員'), ('president', '社長')], max_length=20, verbose_name='承認者ロール')),
                ('step_status', models.CharField(choices=[('pending', '待機中'), ('in_progress', '進行中'), ('approved', '承認済み'), ('rejected', '却下'), ('returned', '差し戻し')], default='pending', max_length=20, verbose_name='ステップステータス')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='期限日時')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='承認日時')),
                ('comment', models.TextField(blank=True, verbose_name='コメント')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '請求書承認ステップ',
                'verbose_name_plural': '請求書承認ステップ一覧',
                'db_table': 'invoice_approval_steps',
                'ordering': ['step_number'],
            },
        ),
        migrations.CreateModel(
            name='InvoiceApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_step', models.IntegerField(default=1, verbose_name='現在のステップ')),
                ('total_steps', models.IntegerField(default=5, verbose_name='総ステップ数')),
                ('workflow_status', models.CharField(choices=[('in_progress', '承認中'), ('completed', '承認完了'), ('rejected', '却下')], default='in_progress', max_length=20, verbose_name='ワークフローステータス')),
                ('started_at', models.DateTimeField(auto_now_add=True, verbose_name='開始日時')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '請求書承認ワークフロー',
                'verbose_name_plural': '請求書承認ワークフロー一覧',
                'db_table': 'invoice_approval_workflows',
            },
        ),
        migrations.CreateModel(
            name='SafetyFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('base_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='対象金額')),
                ('fee_rate', models.DecimalField(decimal_places=4, default=Decimal('0.0030'), help_text='3/1000 = 0.003', max_digits=5, verbose_name='会費率')),
                ('fee_amount', models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='会費金額')),
                ('notification_sent', models.BooleanField(default=False, verbose_name='通知送信済み')),
                ('notification_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='通知送信日時')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '安全衛生協力会費',
                'verbose_name_plural': '安全衛生協力会費一覧',
                'db_table': 'safety_fees',
            },
        ),
        migrations.AddField(
            model_name='company',
            name='bank_account_holder',
            field=models.CharField(blank=True, max_length=100, verbose_name='口座名義'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_account_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='口座番号'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_account_type',
            field=models.CharField(blank=True, choices=[('ordinary', '普通'), ('current', '当座'), ('savings', '貯蓄')], default='ordinary', max_length=20, verbose_name='口座種別'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_branch',
            field=models.CharField(blank=True, max_length=100, verbose_name='支店名'),
        ),
        migrations.AddField(
            model_name='company',
            name='bank_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='銀行名'),
        ),
        migrations.AddField(
            model_name='company',
            name='company_type',
            field=models.CharField(choices=[('client', '発注会社'), ('partner', '協力会社')], default='client', max_length=20, verbose_name='会社種別'),
        ),
        migrations.AddField(
            model_name='company',
            name='contract_start_date',
            field=models.DateField(blank=True, null=True, verbose_name='取引開始日'),
        ),
        migrations.AddField(
            model_name='company',
            name='name_kana',
            field=models.CharField(blank=True, max_length=200, verbose_name='会社名（カナ）'),
        ),
        migrations.AddField(
            model_name='company',
            name='representative_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='代表者名'),
        ),
        migrations.AddField(
            model_name='company',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='constructionsite',
            name='client_name',
            field=models.CharField(blank=True, max_length=200, verbose_name='発注者名'),
        ),
        migrations.AddField(
            model_name='constructionsite',
            name='construction_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='construction_sites', to='invoices.constructiontype', verbose_name='工種'),
        ),
        migrations.AddField(
            model_name='constructionsite',
            name='end_date',
            field=models.DateField(blank=True, null=True, verbose_name='工事終了日'),
        ),
        migrations.AddField(
            model_name='constructionsite',
            name='prime_contractor',
            field=models.CharField(blank=True, max_length=200, verbose_name='元請業者名'),
        ),
        migrations.AddField(
            model_name='constructionsite',
            name='project_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='工事コード'),
        ),
        migrations.AddField(
            model_name='constructionsite',
            name='start_date',
            field=models.DateField(blank=True, null=True, verbose_name='工事開始日'),
        ),
        migrations.AddField(
            model_name='constructionsite',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AddField(
            model_name='department',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='parent_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_departments', to='invoices.department', verbose_name='親部署'),
        ),
        migrations.AddField(
            model_name='department',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='invoicecomment',
            name='parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='invoices.invoicecomment', verbose_name='親コメント'),
        ),
        migrations.AddField(
            model_name='invoicecomment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新日時'),
        ),
        migrations.AlterField(
            model_name='company',
            name='name',
            field=models.CharField(max_length=200, verbose_name='会社名'),
        ),
        migrations.AlterField(
            model_name='company',
            name='tax_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='法人番号'),
        ),
        migrations.AlterField(
            model_name='constructionsite',
            name='location',
            field=models.TextField(blank=True, verbose_name='工事場所'),
        ),
        migrations.AlterField(
            model_name='constructionsite',
            name='name',
            field=models.CharField(max_length=200, verbose_name='工事名'),
        ),
        migrations.AlterField(
            model_name='constructionsite',
            name='total_budget',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15, verbose_name='予算金額'),
        ),
        migrations.AlterField(
            model_name='department',
            name='name',
            field=models.CharField(max_length=100, verbose_name='部署名'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['company_type', 'is_active'], name='invoices_co_company_dc41b4_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionsite',
            index=models.Index(fields=['construction_type', 'supervisor', 'is_completed'], name='invoices_co_constru_cae7c6_idx'),
        ),
        migrations.AddIndex(
            model_name='constructionsite',
            index=models.Index(fields=['start_date', 'end_date'], name='invoices_co_start_d_d5ba32_idx'),
        ),
        migrations.AddIndex(
            model_name='department',
            index=models.Index(fields=['company', 'parent_department'], name='invoices_de_company_e1fe40_idx'),
        ),
        migrations.AddIndex(
            model_name='invoicecomment',
            index=models.Index(fields=['invoice', 'parent_comment'], name='invoice_com_invoice_615f0d_idx'),
        ),
        migrations.AlterModelTable(
            name='invoicecomment',
            table='invoice_comments',
        ),
        migrations.AddField(
            model_name='budget',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budgets', to='invoices.constructionsite', verbose_name='工事現場'),
        ),
        migrations.AddField(
            model_name='constructiontypeusage',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='construction_type_usages', to='invoices.customercompany', verbose_name='協力会社'),
        ),
        migrations.AddField(
            model_name='constructiontypeusage',
            name='construction_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_usages', to='invoices.constructiontype', verbose_name='工種'),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='invoice',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='invoices.invoice', verbose_name='請求書'),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='purchase_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='invoices.purchaseorder', verbose_name='注文書'),
        ),
        migrations.AddField(
            model_name='fileattachment',
            name='uploaded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='アップロード者'),
        ),
        migrations.AddField(
            model_name='invoiceapprovalstep',
            name='approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approval_steps_assigned', to=settings.AUTH_USER_MODEL, verbose_name='承認者'),
        ),
        migrations.AddField(
            model_name='invoiceapprovalworkflow',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workflow', to='invoices.invoice', verbose_name='請求書'),
        ),
        migrations.AddField(
            model_name='invoiceapprovalstep',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='invoices.invoiceapprovalworkflow', verbose_name='ワークフロー'),
        ),
        migrations.AddField(
            model_name='safetyfee',
            name='invoice',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='safety_fee_detail', to='invoices.invoice', verbose_name='請求書'),
        ),
        migrations.AddIndex(
            model_name='budget',
            index=models.Index(fields=['project', 'budget_year'], name='budgets_project_330d3b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='budget',
            unique_together={('project', 'budget_year', 'budget_month')},
        ),
        migrations.AddIndex(
            model_name='constructiontypeusage',
            index=models.Index(fields=['company', 'usage_count'], name='constructio_company_7118bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='constructiontypeusage',
            unique_together={('company', 'construction_type')},
        ),
        migrations.AddIndex(
            model_name='fileattachment',
            index=models.Index(fields=['invoice', 'purchase_order'], name='file_attach_invoice_72c2f3_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceapprovalworkflow',
            index=models.Index(fields=['workflow_status'], name='invoice_app_workflo_e3c785_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceapprovalstep',
            index=models.Index(fields=['workflow', 'step_number'], name='invoice_app_workflo_67bf9e_idx'),
        ),
        migrations.AddIndex(
            model_name='invoiceapprovalstep',
            index=models.Index(fields=['approver', 'step_status'], name='invoice_app_approve_deb6d7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='invoiceapprovalstep',
            unique_together={('workflow', 'step_number')},
        ),
    ]
