# Generated by Django 5.2.5 on 2025-11-27 09:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0007_budget_constructiontypeusage_fileattachment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='can_partner_edit',
            field=models.BooleanField(default=True, help_text='False: 協力会社は承認ボタンのみ（編集不可）', verbose_name='協力会社編集可能'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='has_corrections',
            field=models.BooleanField(default=False, help_text='平野工務店側で赤ペン修正が行われた', verbose_name='修正あり'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='is_returned',
            field=models.BooleanField(default=False, verbose_name='差し戻し済み'),
        ),
        migrations.CreateModel(
            name='InvoiceCorrection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_name', models.CharField(max_length=100, verbose_name='修正フィールド名')),
                ('field_type', models.CharField(choices=[('amount', '金額'), ('quantity', '数量'), ('unit_price', '単価'), ('description', '品名・摘要'), ('other', 'その他')], default='other', max_length=20, verbose_name='フィールド種別')),
                ('original_value', models.TextField(verbose_name='元の値')),
                ('corrected_value', models.TextField(verbose_name='修正後の値')),
                ('correction_reason', models.TextField(verbose_name='修正理由')),
                ('is_approved_by_partner', models.BooleanField(default=False, verbose_name='協力会社承認済み')),
                ('approved_at', models.DateTimeField(blank=True, null=True, verbose_name='承認日時')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='修正日時')),
                ('corrected_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoice_corrections', to=settings.AUTH_USER_MODEL, verbose_name='修正者')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='invoices.invoice', verbose_name='請求書')),
                ('invoice_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='corrections', to='invoices.invoiceitem', verbose_name='請求明細')),
            ],
            options={
                'verbose_name': '請求書修正',
                'verbose_name_plural': '請求書修正一覧',
                'db_table': 'invoice_corrections',
                'ordering': ['-created_at'],
            },
        ),
    ]
