# Generated by Django 5.2.5 on 2025-12-11 07:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0008_invoice_can_partner_edit_invoice_has_corrections_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionsite',
            name='cutoff_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cutoff_sites', to=settings.AUTH_USER_MODEL, verbose_name='打ち切り実行者'),
        ),
        migrations.AddField(
            model_name='constructionsite',
            name='cutoff_date',
            field=models.DateField(blank=True, null=True, verbose_name='打ち切り日'),
        ),
        migrations.AddField(
            model_name='constructionsite',
            name='cutoff_reason',
            field=models.TextField(blank=True, verbose_name='打ち切り理由'),
        ),
        migrations.AddField(
            model_name='constructionsite',
            name='final_invoiced_amount',
            field=models.DecimalField(decimal_places=0, default=0, help_text='打ち切り時点での累計請求額', max_digits=15, verbose_name='最終請求累計額'),
        ),
        migrations.AddField(
            model_name='constructionsite',
            name='is_cutoff',
            field=models.BooleanField(default=False, help_text='打ち切り後は新規請求書作成不可', verbose_name='打ち切り'),
        ),
        migrations.AddField(
            model_name='monthlyinvoiceperiod',
            name='carryover_amount',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=15, verbose_name='繰越金額'),
        ),
        migrations.AddField(
            model_name='monthlyinvoiceperiod',
            name='carryover_reason',
            field=models.TextField(blank=True, verbose_name='繰越理由'),
        ),
        migrations.AddField(
            model_name='monthlyinvoiceperiod',
            name='has_carryover',
            field=models.BooleanField(default=False, verbose_name='繰越あり'),
        ),
        migrations.AddField(
            model_name='monthlyinvoiceperiod',
            name='period_end_date',
            field=models.DateField(blank=True, help_text='当月25日（締日）', null=True, verbose_name='対象期間終了日'),
        ),
        migrations.AddField(
            model_name='monthlyinvoiceperiod',
            name='period_start_date',
            field=models.DateField(blank=True, help_text='前月26日', null=True, verbose_name='対象期間開始日'),
        ),
        migrations.AddField(
            model_name='monthlyinvoiceperiod',
            name='previous_period',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_periods', to='invoices.monthlyinvoiceperiod', verbose_name='前期間'),
        ),
        migrations.AddField(
            model_name='monthlyinvoiceperiod',
            name='submission_deadline',
            field=models.DateField(blank=True, help_text='翌月末日（必着）', null=True, verbose_name='提出期限'),
        ),
        migrations.AddField(
            model_name='monthlyinvoiceperiod',
            name='submission_start_date',
            field=models.DateField(blank=True, help_text='当月26日', null=True, verbose_name='提出開始日'),
        ),
    ]
