# Generated by Django 5.2.5 on 2025-12-25 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0009_add_v2_features'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='partner_acknowledged_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='協力会社承認日時'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='partner_acknowledged_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acknowledged_invoices', to=settings.AUTH_USER_MODEL, verbose_name='協力会社承認者'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='return_note',
            field=models.TextField(blank=True, verbose_name='差し戻し備考'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='return_reason',
            field=models.TextField(blank=True, verbose_name='差し戻し理由'),
        ),
    ]
