# Generated by Django 5.2.5 on 2025-12-25 14:02

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0010_add_return_acknowledgment_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeadlineNotificationBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='表示中')),
                ('target_year', models.IntegerField(verbose_name='対象年')),
                ('target_month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='対象月')),
                ('message_template', models.TextField(default='いつもありがとうございます。{period}のため、請求書の締め日を{deadline_date}とさせていただきます。', help_text='{period}と{deadline_date}が自動置換されます', verbose_name='メッセージテンプレート')),
                ('period_name', models.CharField(help_text='例: 年末年始、ゴールデンウィーク', max_length=100, verbose_name='期間名')),
                ('custom_message', models.TextField(blank=True, help_text='指定した場合、テンプレートより優先されます', verbose_name='カスタムメッセージ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_banners', to=settings.AUTH_USER_MODEL, verbose_name='作成者')),
            ],
            options={
                'verbose_name': '締め日変更バナー',
                'verbose_name_plural': '締め日変更バナー',
                'db_table': 'deadline_notification_banners',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PaymentCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(verbose_name='年')),
                ('month', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)], verbose_name='月')),
                ('payment_date', models.DateField(verbose_name='支払日')),
                ('deadline_date', models.DateField(verbose_name='請求書締め日')),
                ('is_holiday_period', models.BooleanField(default=False, verbose_name='休暇期間フラグ')),
                ('holiday_note', models.TextField(blank=True, verbose_name='休暇に関するお知らせ')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '支払いカレンダー',
                'verbose_name_plural': '支払いカレンダー',
                'db_table': 'payment_calendars',
                'ordering': ['year', 'month'],
                'unique_together': {('year', 'month')},
            },
        ),
        migrations.CreateModel(
            name='UserRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=200, verbose_name='会社名')),
                ('full_name', models.CharField(max_length=100, verbose_name='氏名')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='メールアドレス')),
                ('phone_number', models.CharField(max_length=20, verbose_name='電話番号')),
                ('postal_code', models.CharField(max_length=10, verbose_name='郵便番号')),
                ('address', models.TextField(verbose_name='住所')),
                ('department', models.CharField(blank=True, max_length=100, verbose_name='部署')),
                ('position', models.CharField(blank=True, max_length=100, verbose_name='役職')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('status', models.CharField(choices=[('PENDING', '承認待ち'), ('APPROVED', '承認済み'), ('REJECTED', '却下')], default='PENDING', max_length=20, verbose_name='ステータス')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='申請日時')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='審査日時')),
                ('rejection_reason', models.TextField(blank=True, verbose_name='却下理由')),
                ('created_user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_request', to=settings.AUTH_USER_MODEL, verbose_name='作成されたユーザー')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_registrations', to=settings.AUTH_USER_MODEL, verbose_name='審査者')),
            ],
            options={
                'verbose_name': 'ユーザー登録申請',
                'verbose_name_plural': 'ユーザー登録申請',
                'db_table': 'user_registration_requests',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
