# Generated by Django 5.2.5 on 2026-01-25 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0011_add_payment_calendar_and_banner'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionsite',
            name='site_password',
            field=models.CharField(blank=True, help_text='協力会社が請求書を作成する際に入力するパスワード', max_length=50, null=True, verbose_name='現場パスワード'),
        ),
    ]
