# Generated by Django 5.2.5 on 2026-02-03 12:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0012_constructionsite_site_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='constructionsite',
            name='special_access_expiry',
            field=models.DateField(blank=True, help_text='この日付までは特例パスワードが有効', null=True, verbose_name='特例有効期限'),
        ),
        migrations.AddField(
            model_name='constructionsite',
            name='special_access_password',
            field=models.CharField(blank=True, help_text='締め日過ぎても請求書を作成できるようにするためのパスワード', max_length=50, null=True, verbose_name='特例請求用パスワード'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='approver_position',
            field=models.CharField(choices=[('site_supervisor', '現場監督'), ('managing_director', '常務取締役'), ('senior_managing_director', '専務取締役'), ('president', '代表取締役社長'), ('accountant', '総務部 経理担当'), ('director', '取締役'), ('supervisor', '課長'), ('staff', '一般社員'), ('admin', 'システム管理者')], max_length=30, verbose_name='承認者役職'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('site_supervisor', '現場監督'), ('managing_director', '常務取締役'), ('senior_managing_director', '専務取締役'), ('president', '代表取締役社長'), ('accountant', '総務部 経理担当'), ('director', '取締役'), ('supervisor', '課長'), ('staff', '一般社員'), ('admin', 'システム管理者')], max_length=30, verbose_name='役職'),
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create', '作成'), ('update', '更新'), ('delete', '削除'), ('login', 'ログイン'), ('logout', 'ログアウト'), ('approve', '承認'), ('reject', '否認'), ('remand', '差戻し'), ('cancel', '取り消し'), ('other', 'その他')], max_length=20, verbose_name='操作種別')),
                ('target_model', models.CharField(max_length=50, verbose_name='対象モデル名')),
                ('target_id', models.CharField(blank=True, max_length=50, verbose_name='対象ID')),
                ('target_label', models.CharField(blank=True, help_text='対象オブジェクトの文字列表現', max_length=200, verbose_name='対象ラベル')),
                ('details', models.JSONField(blank=True, default=dict, verbose_name='詳細情報')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IPアドレス')),
                ('user_agent', models.TextField(blank=True, verbose_name='ユーザーエージェント')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='操作日時')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL, verbose_name='操作ユーザー')),
            ],
            options={
                'verbose_name': '操作ログ',
                'verbose_name_plural': '操作ログ一覧',
                'db_table': 'audit_logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
