# Generated by Django 5.2.5 on 2026-02-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0013_constructionsite_special_access_expiry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='is_created_with_special_access',
            field=models.BooleanField(default=False, help_text='特例パスワードを使用して作成されたかどうか', verbose_name='特例作成'),
        ),
    ]
