# Generated by Django 5.2.5 on 2026-02-08 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0014_invoice_is_created_with_special_access'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='ログインIDとして使用されます', max_length=254, unique=True, verbose_name='メールアドレス'),
        ),
    ]
