# Generated by Django 5.2.5 on 2026-02-09

from django.db import migrations

def fix_pending_invoices(apps, schema_editor):
    Invoice = apps.get_model('invoices', 'Invoice')
    ApprovalRoute = apps.get_model('invoices', 'ApprovalRoute')
    ApprovalStep = apps.get_model('invoices', 'ApprovalStep')
    User = apps.get_model('invoices', 'User')

    # Status: pending_approval
    pending_invoices = Invoice.objects.filter(status='pending_approval')
    
    for invoice in pending_invoices:
        # 1. 承認ルートがない場合
        if not invoice.approval_route:
            # デフォルトルートを探す
            route = ApprovalRoute.objects.filter(
                company=invoice.receiving_company,
                is_default=True,
                is_active=True
            ).first()
            if route:
                invoice.approval_route = route
                invoice.save()

        # 2. 現在の承認ステップがない場合 -> ステップ1を設定
        if not invoice.current_approval_step:
            if invoice.approval_route:
                first_step = ApprovalStep.objects.filter(
                    route=invoice.approval_route,
                    step_order=1
                ).first()
                if first_step:
                    invoice.current_approval_step = first_step
                    invoice.save()

        # 3. 現在の承認者がいない場合
        if not invoice.current_approver:
            # ステップ1で、かつ現場監督承認の場合
            if invoice.current_approval_step and invoice.current_approval_step.step_order == 1:
                if invoice.construction_site and invoice.construction_site.supervisor:
                    invoice.current_approver = invoice.construction_site.supervisor
                    invoice.save()
                    print(f"Fixed invoice {invoice.invoice_number}: Assigned supervisor {invoice.construction_site.supervisor.username}")

class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0015_alter_user_email'),
    ]

    operations = [
        migrations.RunPython(fix_pending_invoices),
    ]
