# Generated by Django 5.2.5 on 2026-02-10 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0016_fix_pending_invoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlyinvoiceperiod',
            name='special_access_expiry',
            field=models.DateField(blank=True, help_text='このパスワードが有効な期限', null=True, verbose_name='特例有効期限'),
        ),
        migrations.AddField(
            model_name='monthlyinvoiceperiod',
            name='special_access_password',
            field=models.CharField(blank=True, help_text='締切を過ぎた後に請求書を提出する際の特例パスワード', max_length=100, verbose_name='特例パスワード'),
        ),
        migrations.AlterField(
            model_name='approvalstep',
            name='approver_position',
            field=models.CharField(choices=[('site_supervisor', '現場監督'), ('department_manager', '部長'), ('managing_director', '常務取締役'), ('senior_managing_director', '専務取締役'), ('president', '代表取締役社長'), ('accountant', '総務部 経理担当'), ('director', '取締役'), ('supervisor', '課長'), ('staff', '一般社員'), ('admin', 'システム管理者')], max_length=30, verbose_name='承認者役職'),
        ),
        migrations.AlterField(
            model_name='user',
            name='position',
            field=models.CharField(blank=True, choices=[('site_supervisor', '現場監督'), ('department_manager', '部長'), ('managing_director', '常務取締役'), ('senior_managing_director', '専務取締役'), ('president', '代表取締役社長'), ('accountant', '総務部 経理担当'), ('director', '取締役'), ('supervisor', '課長'), ('staff', '一般社員'), ('admin', 'システム管理者')], max_length=30, verbose_name='役職'),
        ),
    ]
