# Generated by Django 5.2.5 on 2026-02-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0022_fix_user_names_and_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='customercompany',
            name='fax',
            field=models.CharField(blank=True, max_length=20, verbose_name='FAX番号'),
        ),
        migrations.AddField(
            model_name='customercompany',
            name='head_office_address',
            field=models.TextField(blank=True, verbose_name='本社住所'),
        ),
        migrations.AddField(
            model_name='customercompany',
            name='head_office_postal_code',
            field=models.CharField(blank=True, max_length=10, verbose_name='本社郵便番号'),
        ),
        migrations.AddField(
            model_name='customercompany',
            name='invoice_registration_number',
            field=models.CharField(blank=True, help_text='T+13桁の番号（例: T1234567890123）', max_length=20, verbose_name='インボイス番号'),
        ),
        migrations.AddField(
            model_name='customercompany',
            name='name_kana',
            field=models.CharField(blank=True, max_length=200, verbose_name='会社名（ふりがな）'),
        ),
        migrations.AddField(
            model_name='customercompany',
            name='representative_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='代表者名'),
        ),
        migrations.AddField(
            model_name='userregistrationrequest',
            name='company_name_kana',
            field=models.CharField(blank=True, max_length=200, verbose_name='会社名（ふりがな）'),
        ),
        migrations.AddField(
            model_name='userregistrationrequest',
            name='fax_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='FAX番号'),
        ),
        migrations.AddField(
            model_name='userregistrationrequest',
            name='head_office_address',
            field=models.TextField(blank=True, verbose_name='本社住所'),
        ),
        migrations.AddField(
            model_name='userregistrationrequest',
            name='invoice_registration_number',
            field=models.CharField(blank=True, help_text='T+13桁の番号（例: T1234567890123）', max_length=20, verbose_name='インボイス番号'),
        ),
        migrations.AddField(
            model_name='userregistrationrequest',
            name='representative_name',
            field=models.CharField(blank=True, max_length=100, verbose_name='代表者名'),
        ),
    ]
