"""
Django settings for keyron_project project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import dj_database_url
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-k=7l0(k#%0(^)woy)ktw#y@_s+)el935so!k5+sg8%nf8c(k1^')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', '*').split(',')


# Application definition

INSTALLED_APPS = [
    # Django標準アプリ
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    
    # カスタムアプリ
    'invoices',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise追加
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS対応
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'keyron_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'invoices/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'keyron_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASE_URLが設定されている場合はそちらを使用、なければSQLiteを使用
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    # DATABASE_URLからデータベース設定を取得
    db_config = dj_database_url.parse(DATABASE_URL)
    # NAMEが空の場合はURLから取得を試みる（特殊文字対策）
    if not db_config.get('NAME'):
        # URLから直接データベース名を抽出（末尾のパス部分）
        try:
            from urllib.parse import urlparse
            parsed = urlparse(DATABASE_URL)
            db_config['NAME'] = parsed.path.lstrip('/')
        except Exception:
            pass
    db_config['CONN_MAX_AGE'] = 600
    DATABASES = {
        'default': db_config
    }
else:
    # ローカル開発環境: SQLiteを使用
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'invoices.User'

# 認証バックエンド
AUTHENTICATION_BACKENDS = [
    'invoices.backends.CustomAuthBackend',  # カスタムバックエンド
    'django.contrib.auth.backends.ModelBackend',  # フォールバック
]




# Login/Logout URLs
LOGIN_REDIRECT_URL = '/invoices/upload/'


# ====================
# REST Framework設定
# ====================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
}

# ====================
# JWT設定
# ====================
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
}

# ====================
# CORS設定
# ====================
# 開発環境用のデフォルトオリジン
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React開発サーバー
    "http://127.0.0.1:3000",
    "http://localhost:3002",  # React開発サーバー (別ポート)
    "http://127.0.0.1:3002",
    "https://main.d16cyywei73ulq.amplifyapp.com", # Amplify Frontend
]

# 環境変数から追加のOriginを読み込む（本番用）
env_origins = os.environ.get('CORS_ALLOWED_ORIGINS')
if env_origins:
    CORS_ALLOWED_ORIGINS.extend([origin.strip() for origin in env_origins.split(',') if origin.strip()])

# 本番環境で全オリジン許可が必要な場合（テスト用）
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'False') == 'True'

CORS_ALLOW_CREDENTIALS = True

# 許可するヘッダー
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# 許可するHTTPメソッド
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# ====================
# メール設定
# ====================
# 開発環境: コンソールに出力
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

# 本番環境用（SMTPサーバー設定）
# EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
# EMAIL_HOST = 'smtp.example.com'
# EMAIL_PORT = 587
# EMAIL_USE_TLS = True
# EMAIL_HOST_USER = 'your-email@example.com'
# EMAIL_HOST_PASSWORD = 'your-password'

DEFAULT_FROM_EMAIL = 'noreply@hirano-koumuten.co.jp'
EMAIL_SUBJECT_PREFIX = '[KEYRON BIM] '

# フロントエンドURL（ユーザー登録完了メール用）
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')

# 管理者メールアドレス（ユーザー登録申請通知用）
ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL', 'admin@hirano-koumuten.co.jp')

# ====================
# 請求書システム設定
# ====================
INVOICE_SETTINGS = {
    # 月次締め日（毎月25日）
    'MONTHLY_DEADLINE_DAY': 25,
    
    # 訂正可能期間（日数）
    'CORRECTION_PERIOD_DAYS': 2,
    
    # 安全衛生協力会費
    'SAFETY_FEE_THRESHOLD': 100000,  # 10万円以上
    'SAFETY_FEE_RATE': 0.003,  # 3/1000
    
    # 予算アラート閾値
    'BUDGET_ALERT_80': 80,
    'BUDGET_ALERT_90': 90,
    'BUDGET_ALERT_100': 100,
    
    # 承認リマインド（日数）
    'APPROVAL_REMINDER_DAYS': [3, 1],  # 締切3日前、1日前
}

# ====================
# ログ設定
# ====================
# ログディレクトリの作成（存在しない場合エラーになるため）
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'app.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'invoices': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}

# ====================
# EMERGENCY DEBUG SETTINGS
# ====================
# エラー詳細を表示し、CORS/Host制限を全開放して接続を優先する
DEBUG = True
ALLOWED_HOSTS = ['*']
CORS_ALLOW_ALL_ORIGINS = True

# DB接続エラー回避：環境変数のDB名が間違っている可能性があるため強制的に修正
if 'default' in DATABASES:
    DATABASES['default']['NAME'] = 'postgres'
