"""
Django settings for keyron_project project.

Generated by 'django-admin startproject' using Django 5.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
import sys
import logging
import dj_database_url
from pathlib import Path
from datetime import timedelta

logger = logging.getLogger(__name__)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('SECRET_KEY', 'django-insecure-k=7l0(k#%0(^)woy)ktw#y@_s+)el935so!k5+sg8%nf8c(k1^')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = os.environ.get('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')


# Application definition

INSTALLED_APPS = [
    # Django標準アプリ
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    
    # Third party apps
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    'django_filters',
    
    # カスタムアプリ
    'invoices',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise追加
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # CORS対応
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'keyron_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'invoices/templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'keyron_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# DATABASE_URLが設定されている場合はそちらを使用、なければSQLiteを使用
DATABASE_URL = os.environ.get('DATABASE_URL')

if DATABASE_URL:
    masked_url = DATABASE_URL.split('@')[-1] if '@' in DATABASE_URL else 'HIDDEN'
    logger.info(f"DATABASE_URL detected. Host info: {masked_url}")
    
    db_config = dj_database_url.parse(DATABASE_URL, conn_max_age=600)
    
    # DB名を環境変数から取得（デフォルト: postgres）
    db_name_override = os.environ.get('DB_NAME_OVERRIDE', 'postgres')
    original_name = db_config.get('NAME')
    if original_name != db_name_override:
        logger.warning(f"DB Name overridden: {original_name} -> {db_name_override}")
        db_config['NAME'] = db_name_override
    
    DATABASES = {
        'default': db_config
    }
else:
    logger.info("No DATABASE_URL found. Using SQLite.")
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'ja'

TIME_ZONE = 'Asia/Tokyo'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'static'),
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'


# Media files (User uploaded files)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Custom User Model
AUTH_USER_MODEL = 'invoices.User'

# 認証バックエンド
AUTHENTICATION_BACKENDS = [
    'invoices.backends.CustomAuthBackend',  # カスタムバックエンド
    'django.contrib.auth.backends.ModelBackend',  # フォールバック
]



# Login/Logout URLs
LOGIN_REDIRECT_URL = '/invoices/upload/'


# ====================
# REST Framework設定
# ====================
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 10,
    'DEFAULT_FILTER_BACKENDS': [
        'django_filters.rest_framework.DjangoFilterBackend',
        'rest_framework.filters.SearchFilter',
        'rest_framework.filters.OrderingFilter',
    ],
}

# ====================
# JWT設定
# ====================
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(hours=1),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=7),
    'ROTATE_REFRESH_TOKENS': True,
    'TOKEN_OBTAIN_SERIALIZER': 'invoices.jwt_serializers.EmailTokenObtainPairSerializer',
}

# ====================
# CORS設定
# ====================
# 開発環境用のデフォルトオリジン
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",  # React開発サーバー
    "http://127.0.0.1:3000",
    "http://localhost:3002",  # React開発サーバー (別ポート)
    "http://127.0.0.1:3002",
]

# 環境変数から追加のOriginを読み込む（本番用）
env_origins = os.environ.get('CORS_ALLOWED_ORIGINS')
if env_origins:
    CORS_ALLOWED_ORIGINS.extend([origin.strip() for origin in env_origins.split(',') if origin.strip()])

# FRONTEND_URLが設定されている場合はCORS許可に追加
frontend_url = os.environ.get('FRONTEND_URL')
if frontend_url:
    CORS_ALLOWED_ORIGINS.append(frontend_url.rstrip('/'))

# 本番環境で全オリジン許可が必要な場合（テスト用）
CORS_ALLOW_ALL_ORIGINS = os.environ.get('CORS_ALLOW_ALL_ORIGINS', 'False') == 'True'

CORS_ALLOW_CREDENTIALS = True

# ====================
# CSRF設定
# ====================
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "https://chwnptmkcn.ap-southeast-2.awsapprunner.com",  # App Runner backend
]

# 環境変数から追加のOriginを読み込む
if frontend_url:
    CSRF_TRUSTED_ORIGINS.append(frontend_url.rstrip('/'))

env_csrf_origins = os.environ.get('CSRF_TRUSTED_ORIGINS')
if env_csrf_origins:
    CSRF_TRUSTED_ORIGINS.extend([origin.strip() for origin in env_csrf_origins.split(',') if origin.strip()])

# 許可するヘッダー
CORS_ALLOW_HEADERS = [
    'accept',
    'accept-encoding',
    'authorization',
    'content-type',
    'dnt',
    'origin',
    'user-agent',
    'x-csrftoken',
    'x-requested-with',
]

# 許可するHTTPメソッド
CORS_ALLOW_METHODS = [
    'DELETE',
    'GET',
    'OPTIONS',
    'PATCH',
    'POST',
    'PUT',
]

# ====================
# メール設定
# ====================
# 環境変数で切り替え（デフォルト: 開発用コンソール出力）
EMAIL_BACKEND = os.environ.get(
    'EMAIL_BACKEND',
    'django.core.mail.backends.console.EmailBackend'
)

# AWS SES / SMTP 本番設定（環境変数で注入）
EMAIL_HOST = os.environ.get('EMAIL_HOST', 'email-smtp.ap-northeast-1.amazonaws.com')
EMAIL_PORT = int(os.environ.get('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.environ.get('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD', '')

DEFAULT_FROM_EMAIL = os.environ.get('DEFAULT_FROM_EMAIL', 'noreply@hirano-koumuten.co.jp')
EMAIL_SUBJECT_PREFIX = '[平野工務店-BIM] '

# フロントエンドURL（ユーザー登録完了メール用）
FRONTEND_URL = os.environ.get('FRONTEND_URL', 'http://localhost:3000')

# 管理者メールアドレス（ユーザー登録申請通知用）
ADMIN_EMAIL = os.environ.get('ADMIN_EMAIL', 'admin@hirano-koumuten.co.jp')

# ====================
# 請求書システム設定
# ====================
INVOICE_SETTINGS = {
    # 月次締め日（毎月25日）
    'MONTHLY_DEADLINE_DAY': 25,
    
    # 訂正可能期間（日数）
    'CORRECTION_PERIOD_DAYS': 2,
    
    # 安全衛生協力会費
    'SAFETY_FEE_THRESHOLD': 100000,  # 10万円以上
    'SAFETY_FEE_RATE': 0.003,  # 3/1000
    
    # 予算アラート閾値
    'BUDGET_ALERT_80': 80,
    'BUDGET_ALERT_90': 90,
    'BUDGET_ALERT_100': 100,
    
    # 承認リマインド（日数）
    'APPROVAL_REMINDER_DAYS': [3, 1],  # 締切3日前、1日前
}

# ====================
# ログ設定
# ====================
# ログディレクトリの作成（存在しない場合エラーになるため）
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.FileHandler',
            'filename': BASE_DIR / 'logs' / 'app.log',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        'invoices': {
            'handlers': ['console'],
            'level': 'INFO',
        },
    },
}
